# Generated by Django 2.1.2 on 2018-10-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samosval',
            fields=[
                ('board_num', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('mark', models.CharField(max_length=50)),
                ('max_cargo', models.IntegerField()),
                ('current_cargo', models.IntegerField()),
            ],
        ),
    ]
